"""add project report, drop chronicle_references

Revision ID: 223fbc3bf2f0
Revises: 8ababb95b4fe
Create Date: 2026-06-06 19:46:03.901671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '223fbc3bf2f0'
down_revision: Union[str, None] = '8ababb95b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chronicle_references_is_deleted'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_project_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_section_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_create_datetime'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_creator_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_dept_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_update_datetime'), table_name='chronicle_references')
    op.drop_table('chronicle_references')
    op.add_column('chronicle_projects', sa.Column('report', sa.Text(), nullable=True, comment='工作流总报告'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chronicle_projects', 'report')
    op.create_table('chronicle_references',
    sa.Column('project_id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='所属项目ID'),
    sa.Column('section_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='关联章节ID'),
    sa.Column('ref_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='引用标识如ref_001'),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='kg_file/kb_document/book/periodical/archive/website/other'),
    sa.Column('source_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='来源文件ID'),
    sa.Column('source_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='来源标题'),
    sa.Column('author', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='作者'),
    sa.Column('publisher', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='出版者'),
    sa.Column('year', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('volume', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='卷期'),
    sa.Column('page_info', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='页码'),
    sa.Column('citation_text', sa.TEXT(), autoincrement=False, nullable=True, comment='格式化引文'),
    sa.Column('quote_text', sa.TEXT(), autoincrement=False, nullable=True, comment='原文引述'),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='置信度'),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否已验证'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id', name=op.f('chronicle_references_pkey'))
    )
    op.create_index(op.f('ix_chronicle_references_sys_update_datetime'), 'chronicle_references', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_dept_id'), 'chronicle_references', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_creator_id'), 'chronicle_references', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_create_datetime'), 'chronicle_references', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_references_section_id'), 'chronicle_references', ['section_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_project_id'), 'chronicle_references', ['project_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_is_deleted'), 'chronicle_references', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
