"""add workflow_conversation table

Revision ID: 24779f682e06
Revises: bcabe17b0685
Create Date: 2026-06-12 11:19:18.484596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24779f682e06'
down_revision: Union[str, None] = 'bcabe17b0685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_workflow_conversation',
    sa.Column('workflow_def_id', sa.String(length=21), nullable=False, comment='关联的工作流定义ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题（从首条消息自动生成）'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['workflow_def_id'], ['ai_workflow_def.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_conversation_is_deleted'), 'ai_workflow_conversation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_workflow_conversation_sys_create_datetime'), 'ai_workflow_conversation', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_conversation_sys_creator_id'), 'ai_workflow_conversation', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_conversation_sys_dept_id'), 'ai_workflow_conversation', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_conversation_sys_update_datetime'), 'ai_workflow_conversation', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_conversation_workflow_def_id'), 'ai_workflow_conversation', ['workflow_def_id'], unique=False)
    op.add_column('ai_workflow_instance', sa.Column('conversation_id', sa.String(length=21), nullable=True, comment='所属会话ID（多轮对话时使用）'))
    op.add_column('ai_workflow_instance', sa.Column('turn_index', sa.Integer(), nullable=True, comment='会话中的轮次序号'))
    op.create_index(op.f('ix_ai_workflow_instance_conversation_id'), 'ai_workflow_instance', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'ai_workflow_instance', 'ai_workflow_conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_workflow_instance', type_='foreignkey')
    op.drop_index(op.f('ix_ai_workflow_instance_conversation_id'), table_name='ai_workflow_instance')
    op.drop_column('ai_workflow_instance', 'turn_index')
    op.drop_column('ai_workflow_instance', 'conversation_id')
    op.drop_index(op.f('ix_ai_workflow_conversation_workflow_def_id'), table_name='ai_workflow_conversation')
    op.drop_index(op.f('ix_ai_workflow_conversation_sys_update_datetime'), table_name='ai_workflow_conversation')
    op.drop_index(op.f('ix_ai_workflow_conversation_sys_dept_id'), table_name='ai_workflow_conversation')
    op.drop_index(op.f('ix_ai_workflow_conversation_sys_creator_id'), table_name='ai_workflow_conversation')
    op.drop_index(op.f('ix_ai_workflow_conversation_sys_create_datetime'), table_name='ai_workflow_conversation')
    op.drop_index(op.f('ix_ai_workflow_conversation_is_deleted'), table_name='ai_workflow_conversation')
    op.drop_table('ai_workflow_conversation')
    # ### end Alembic commands ###
