"""add is_public to knowledge base

Revision ID: 430947c9480f
Revises: 45727fb9b0f9
Create Date: 2026-06-10 03:50:28.650103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430947c9480f'
down_revision: Union[str, None] = '45727fb9b0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_knowledge_base', sa.Column('is_public', sa.Boolean(), nullable=True, comment='全员可见'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_knowledge_base', 'is_public')
    # ### end Alembic commands ###
