"""add dept and user level kb permissions

Revision ID: 45727fb9b0f9
Revises: 223fbc3bf2f0
Create Date: 2026-06-10 03:08:04.712036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45727fb9b0f9'
down_revision: Union[str, None] = '223fbc3bf2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_workflow_def',
    sa.Column('name', sa.String(length=200), nullable=False, comment='工作流名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('nodes', sa.Text(), nullable=False, comment='节点定义 JSON: [{id, type, params, position}]'),
    sa.Column('edges', sa.Text(), nullable=False, comment='边定义 JSON: [{source, target, sourceHandle, targetHandle}]'),
    sa.Column('global_params', sa.Text(), nullable=True, comment='全局参数 JSON'),
    sa.Column('is_published', sa.Boolean(), nullable=True, comment='是否已发布'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_def_is_deleted'), 'ai_workflow_def', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_workflow_def_name'), 'ai_workflow_def', ['name'], unique=False)
    op.create_index(op.f('ix_ai_workflow_def_sys_create_datetime'), 'ai_workflow_def', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_def_sys_creator_id'), 'ai_workflow_def', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_def_sys_dept_id'), 'ai_workflow_def', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_def_sys_update_datetime'), 'ai_workflow_def', ['sys_update_datetime'], unique=False)
    op.create_table('ai_workflow_instance',
    sa.Column('workflow_def_id', sa.String(length=21), nullable=False, comment='关联的工作流定义ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/running/completed/failed/cancelled'),
    sa.Column('input_params', sa.Text(), nullable=True, comment='输入参数 JSON'),
    sa.Column('output_result', sa.Text(), nullable=True, comment='最终输出结果 JSON'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始执行时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='执行完成时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['workflow_def_id'], ['ai_workflow_def.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_instance_is_deleted'), 'ai_workflow_instance', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_workflow_instance_status'), 'ai_workflow_instance', ['status'], unique=False)
    op.create_index(op.f('ix_ai_workflow_instance_sys_create_datetime'), 'ai_workflow_instance', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_instance_sys_creator_id'), 'ai_workflow_instance', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_instance_sys_dept_id'), 'ai_workflow_instance', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_instance_sys_update_datetime'), 'ai_workflow_instance', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_instance_workflow_def_id'), 'ai_workflow_instance', ['workflow_def_id'], unique=False)
    op.create_table('rag_knowledge_base_dept',
    sa.Column('dept_id', sa.String(length=21), nullable=False, comment='部门ID'),
    sa.Column('kb_id', sa.String(length=21), nullable=False, comment='知识库ID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['dept_id'], ['core_dept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['rag_knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_id', 'kb_id', name='uq_dept_kb')
    )
    op.create_index(op.f('ix_rag_knowledge_base_dept_dept_id'), 'rag_knowledge_base_dept', ['dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_dept_is_deleted'), 'rag_knowledge_base_dept', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_dept_kb_id'), 'rag_knowledge_base_dept', ['kb_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_dept_sys_create_datetime'), 'rag_knowledge_base_dept', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_dept_sys_creator_id'), 'rag_knowledge_base_dept', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_dept_sys_dept_id'), 'rag_knowledge_base_dept', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_dept_sys_update_datetime'), 'rag_knowledge_base_dept', ['sys_update_datetime'], unique=False)
    op.create_table('rag_knowledge_base_user',
    sa.Column('user_id', sa.String(length=21), nullable=False, comment='用户ID'),
    sa.Column('kb_id', sa.String(length=21), nullable=False, comment='知识库ID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['kb_id'], ['rag_knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kb_id', name='uq_user_kb')
    )
    op.create_index(op.f('ix_rag_knowledge_base_user_is_deleted'), 'rag_knowledge_base_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_user_kb_id'), 'rag_knowledge_base_user', ['kb_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_user_sys_create_datetime'), 'rag_knowledge_base_user', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_user_sys_creator_id'), 'rag_knowledge_base_user', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_user_sys_dept_id'), 'rag_knowledge_base_user', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_user_sys_update_datetime'), 'rag_knowledge_base_user', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_user_user_id'), 'rag_knowledge_base_user', ['user_id'], unique=False)
    op.create_table('ai_workflow_node_log',
    sa.Column('instance_id', sa.String(length=21), nullable=False, comment='关联的执行实例ID'),
    sa.Column('node_id', sa.String(length=100), nullable=False, comment='节点ID'),
    sa.Column('node_type', sa.String(length=100), nullable=False, comment='节点类型'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/running/completed/failed'),
    sa.Column('input_data', sa.Text(), nullable=True, comment='输入数据 JSON'),
    sa.Column('output_data', sa.Text(), nullable=True, comment='输出数据 JSON'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始执行时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='执行完成时间'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='执行耗时(毫秒)'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['instance_id'], ['ai_workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_node_log_instance_id'), 'ai_workflow_node_log', ['instance_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_node_log_is_deleted'), 'ai_workflow_node_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_workflow_node_log_sys_create_datetime'), 'ai_workflow_node_log', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_node_log_sys_creator_id'), 'ai_workflow_node_log', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_node_log_sys_dept_id'), 'ai_workflow_node_log', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_node_log_sys_update_datetime'), 'ai_workflow_node_log', ['sys_update_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_workflow_node_log_sys_update_datetime'), table_name='ai_workflow_node_log')
    op.drop_index(op.f('ix_ai_workflow_node_log_sys_dept_id'), table_name='ai_workflow_node_log')
    op.drop_index(op.f('ix_ai_workflow_node_log_sys_creator_id'), table_name='ai_workflow_node_log')
    op.drop_index(op.f('ix_ai_workflow_node_log_sys_create_datetime'), table_name='ai_workflow_node_log')
    op.drop_index(op.f('ix_ai_workflow_node_log_is_deleted'), table_name='ai_workflow_node_log')
    op.drop_index(op.f('ix_ai_workflow_node_log_instance_id'), table_name='ai_workflow_node_log')
    op.drop_table('ai_workflow_node_log')
    op.drop_index(op.f('ix_rag_knowledge_base_user_user_id'), table_name='rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_user_sys_update_datetime'), table_name='rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_user_sys_dept_id'), table_name='rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_user_sys_creator_id'), table_name='rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_user_sys_create_datetime'), table_name='rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_user_kb_id'), table_name='rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_user_is_deleted'), table_name='rag_knowledge_base_user')
    op.drop_table('rag_knowledge_base_user')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_sys_update_datetime'), table_name='rag_knowledge_base_dept')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_sys_dept_id'), table_name='rag_knowledge_base_dept')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_sys_creator_id'), table_name='rag_knowledge_base_dept')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_sys_create_datetime'), table_name='rag_knowledge_base_dept')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_kb_id'), table_name='rag_knowledge_base_dept')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_is_deleted'), table_name='rag_knowledge_base_dept')
    op.drop_index(op.f('ix_rag_knowledge_base_dept_dept_id'), table_name='rag_knowledge_base_dept')
    op.drop_table('rag_knowledge_base_dept')
    op.drop_index(op.f('ix_ai_workflow_instance_workflow_def_id'), table_name='ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_instance_sys_update_datetime'), table_name='ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_instance_sys_dept_id'), table_name='ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_instance_sys_creator_id'), table_name='ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_instance_sys_create_datetime'), table_name='ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_instance_status'), table_name='ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_instance_is_deleted'), table_name='ai_workflow_instance')
    op.drop_table('ai_workflow_instance')
    op.drop_index(op.f('ix_ai_workflow_def_sys_update_datetime'), table_name='ai_workflow_def')
    op.drop_index(op.f('ix_ai_workflow_def_sys_dept_id'), table_name='ai_workflow_def')
    op.drop_index(op.f('ix_ai_workflow_def_sys_creator_id'), table_name='ai_workflow_def')
    op.drop_index(op.f('ix_ai_workflow_def_sys_create_datetime'), table_name='ai_workflow_def')
    op.drop_index(op.f('ix_ai_workflow_def_name'), table_name='ai_workflow_def')
    op.drop_index(op.f('ix_ai_workflow_def_is_deleted'), table_name='ai_workflow_def')
    op.drop_table('ai_workflow_def')
    # ### end Alembic commands ###
