"""add chronicle_project conversation_id

Revision ID: 8ababb95b4fe
Revises: cbcdd0610e0e
Create Date: 2026-06-06 19:29:35.010070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ababb95b4fe'
down_revision: Union[str, None] = 'cbcdd0610e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chronicle_projects', sa.Column('conversation_id', sa.String(length=21), nullable=True, comment='关联对话ID'))
    op.create_index(op.f('ix_chronicle_projects_conversation_id'), 'chronicle_projects', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chronicle_projects_conversation_id'), table_name='chronicle_projects')
    op.drop_column('chronicle_projects', 'conversation_id')
    # ### end Alembic commands ###
