"""add ai_workflow team_config

Revision ID: 9ccdc473c342
Revises: 430947c9480f
Create Date: 2026-06-11 19:13:35.529761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccdc473c342'
down_revision: Union[str, None] = '430947c9480f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_workflow_team_config',
    sa.Column('name', sa.String(length=200), nullable=False, comment='团队名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('team_rules', sa.Text(), nullable=False, comment='团队规则与目标描述'),
    sa.Column('start_role', sa.String(length=50), nullable=False, comment='起始角色名称'),
    sa.Column('roles', sa.Text(), nullable=False, comment='角色定义 JSON'),
    sa.Column('yaml_source', sa.Text(), nullable=True, comment='原始YAML内容（可选）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workflow_team_config_is_deleted'), 'ai_workflow_team_config', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_workflow_team_config_name'), 'ai_workflow_team_config', ['name'], unique=False)
    op.create_index(op.f('ix_ai_workflow_team_config_sys_create_datetime'), 'ai_workflow_team_config', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_ai_workflow_team_config_sys_creator_id'), 'ai_workflow_team_config', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_team_config_sys_dept_id'), 'ai_workflow_team_config', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_team_config_sys_update_datetime'), 'ai_workflow_team_config', ['sys_update_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_workflow_team_config_sys_update_datetime'), table_name='ai_workflow_team_config')
    op.drop_index(op.f('ix_ai_workflow_team_config_sys_dept_id'), table_name='ai_workflow_team_config')
    op.drop_index(op.f('ix_ai_workflow_team_config_sys_creator_id'), table_name='ai_workflow_team_config')
    op.drop_index(op.f('ix_ai_workflow_team_config_sys_create_datetime'), table_name='ai_workflow_team_config')
    op.drop_index(op.f('ix_ai_workflow_team_config_name'), table_name='ai_workflow_team_config')
    op.drop_index(op.f('ix_ai_workflow_team_config_is_deleted'), table_name='ai_workflow_team_config')
    op.drop_table('ai_workflow_team_config')
    # ### end Alembic commands ###
