"""add chronicle writer tables

Revision ID: cbcdd0610e0e
Revises: db144068a72c
Create Date: 2026-06-03 02:44:10.126506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcdd0610e0e'
down_revision: Union[str, None] = 'db144068a72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronicle_projects',
    sa.Column('title', sa.String(length=200), nullable=False, comment='志书标题'),
    sa.Column('subtitle', sa.String(length=500), nullable=True, comment='副标题/卷名'),
    sa.Column('chronicle_type', sa.String(length=50), nullable=False, comment='类型: town/county/special'),
    sa.Column('region_name', sa.String(length=200), nullable=True, comment='地区名称'),
    sa.Column('scope_description', sa.Text(), nullable=True, comment='编纂范围/断限说明'),
    sa.Column('editorial_notes', sa.Text(), nullable=True, comment='凡例'),
    sa.Column('outline_json', sa.JSON(), nullable=True, comment='大纲树(JSON)'),
    sa.Column('kb_ids', sa.JSON(), nullable=True, comment='选定的知识库ID列表'),
    sa.Column('file_ids', sa.JSON(), nullable=True, comment='选定的文件ID列表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='写作配置覆盖'),
    sa.Column('workflow_run_id', sa.String(length=100), nullable=True, comment='LangGraph run ID'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='总字数'),
    sa.Column('user_id', sa.String(length=21), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_projects_is_deleted'), 'chronicle_projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chronicle_projects_status'), 'chronicle_projects', ['status'], unique=False)
    op.create_index(op.f('ix_chronicle_projects_sys_create_datetime'), 'chronicle_projects', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_projects_sys_creator_id'), 'chronicle_projects', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_chronicle_projects_sys_dept_id'), 'chronicle_projects', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_chronicle_projects_sys_update_datetime'), 'chronicle_projects', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_projects_user_id'), 'chronicle_projects', ['user_id'], unique=False)
    op.create_table('chronicle_references',
    sa.Column('project_id', sa.String(length=21), nullable=False, comment='所属项目ID'),
    sa.Column('section_id', sa.String(length=21), nullable=True, comment='关联章节ID'),
    sa.Column('ref_key', sa.String(length=100), nullable=False, comment='引用标识如ref_001'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='kg_file/kb_document/book/periodical/archive/website/other'),
    sa.Column('source_id', sa.String(length=21), nullable=True, comment='来源文件ID'),
    sa.Column('source_title', sa.String(length=500), nullable=True, comment='来源标题'),
    sa.Column('author', sa.String(length=200), nullable=True, comment='作者'),
    sa.Column('publisher', sa.String(length=200), nullable=True, comment='出版者'),
    sa.Column('year', sa.String(length=20), nullable=True, comment='年份'),
    sa.Column('volume', sa.String(length=50), nullable=True, comment='卷期'),
    sa.Column('page_info', sa.String(length=100), nullable=True, comment='页码'),
    sa.Column('citation_text', sa.Text(), nullable=True, comment='格式化引文'),
    sa.Column('quote_text', sa.Text(), nullable=True, comment='原文引述'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度'),
    sa.Column('verified', sa.Boolean(), nullable=True, comment='是否已验证'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_references_is_deleted'), 'chronicle_references', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chronicle_references_project_id'), 'chronicle_references', ['project_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_section_id'), 'chronicle_references', ['section_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_create_datetime'), 'chronicle_references', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_creator_id'), 'chronicle_references', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_dept_id'), 'chronicle_references', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_chronicle_references_sys_update_datetime'), 'chronicle_references', ['sys_update_datetime'], unique=False)
    op.create_table('chronicle_reviews',
    sa.Column('project_id', sa.String(length=21), nullable=False, comment='所属项目ID'),
    sa.Column('section_id', sa.String(length=21), nullable=True, comment='关联章节ID'),
    sa.Column('review_type', sa.String(length=30), nullable=False, comment='fact/style/citation/structure/logic'),
    sa.Column('reviewer_agent', sa.String(length=50), nullable=False, comment='审校Agent名称'),
    sa.Column('issue', sa.Text(), nullable=False, comment='问题描述'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='critical/major/minor/suggestion'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='修改建议'),
    sa.Column('resolved', sa.Boolean(), nullable=True, comment='是否已解决'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='解决时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_reviews_is_deleted'), 'chronicle_reviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chronicle_reviews_project_id'), 'chronicle_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_chronicle_reviews_section_id'), 'chronicle_reviews', ['section_id'], unique=False)
    op.create_index(op.f('ix_chronicle_reviews_sys_create_datetime'), 'chronicle_reviews', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_reviews_sys_creator_id'), 'chronicle_reviews', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_chronicle_reviews_sys_dept_id'), 'chronicle_reviews', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_chronicle_reviews_sys_update_datetime'), 'chronicle_reviews', ['sys_update_datetime'], unique=False)
    op.create_table('chronicle_sections',
    sa.Column('project_id', sa.String(length=21), nullable=False, comment='所属项目ID'),
    sa.Column('parent_id', sa.String(length=21), nullable=True, comment='父章节ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='章/节/目标题'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级: 1=章 2=节 3=目 4=子目'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='同级排序'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文(HTML)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending/writing/reviewing/approved'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='本节约字数'),
    sa.Column('research_data', sa.JSON(), nullable=True, comment='该节的研究资料缓存'),
    sa.Column('agent_notes', sa.Text(), nullable=True, comment='智能体写作备注'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_sections_is_deleted'), 'chronicle_sections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chronicle_sections_parent_id'), 'chronicle_sections', ['parent_id'], unique=False)
    op.create_index(op.f('ix_chronicle_sections_project_id'), 'chronicle_sections', ['project_id'], unique=False)
    op.create_index(op.f('ix_chronicle_sections_sys_create_datetime'), 'chronicle_sections', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_sections_sys_creator_id'), 'chronicle_sections', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_chronicle_sections_sys_dept_id'), 'chronicle_sections', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_chronicle_sections_sys_update_datetime'), 'chronicle_sections', ['sys_update_datetime'], unique=False)
    op.create_table('chronicle_workflow_logs',
    sa.Column('project_id', sa.String(length=21), nullable=False, comment='所属项目ID'),
    sa.Column('stage', sa.String(length=50), nullable=False, comment='节点名称'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='start/complete/error/interrupt/resume'),
    sa.Column('message', sa.Text(), nullable=True, comment='日志消息'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='额外数据'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_workflow_logs_is_deleted'), 'chronicle_workflow_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chronicle_workflow_logs_project_id'), 'chronicle_workflow_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_chronicle_workflow_logs_sys_create_datetime'), 'chronicle_workflow_logs', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_chronicle_workflow_logs_sys_creator_id'), 'chronicle_workflow_logs', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_chronicle_workflow_logs_sys_dept_id'), 'chronicle_workflow_logs', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_chronicle_workflow_logs_sys_update_datetime'), 'chronicle_workflow_logs', ['sys_update_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chronicle_workflow_logs_sys_update_datetime'), table_name='chronicle_workflow_logs')
    op.drop_index(op.f('ix_chronicle_workflow_logs_sys_dept_id'), table_name='chronicle_workflow_logs')
    op.drop_index(op.f('ix_chronicle_workflow_logs_sys_creator_id'), table_name='chronicle_workflow_logs')
    op.drop_index(op.f('ix_chronicle_workflow_logs_sys_create_datetime'), table_name='chronicle_workflow_logs')
    op.drop_index(op.f('ix_chronicle_workflow_logs_project_id'), table_name='chronicle_workflow_logs')
    op.drop_index(op.f('ix_chronicle_workflow_logs_is_deleted'), table_name='chronicle_workflow_logs')
    op.drop_table('chronicle_workflow_logs')
    op.drop_index(op.f('ix_chronicle_sections_sys_update_datetime'), table_name='chronicle_sections')
    op.drop_index(op.f('ix_chronicle_sections_sys_dept_id'), table_name='chronicle_sections')
    op.drop_index(op.f('ix_chronicle_sections_sys_creator_id'), table_name='chronicle_sections')
    op.drop_index(op.f('ix_chronicle_sections_sys_create_datetime'), table_name='chronicle_sections')
    op.drop_index(op.f('ix_chronicle_sections_project_id'), table_name='chronicle_sections')
    op.drop_index(op.f('ix_chronicle_sections_parent_id'), table_name='chronicle_sections')
    op.drop_index(op.f('ix_chronicle_sections_is_deleted'), table_name='chronicle_sections')
    op.drop_table('chronicle_sections')
    op.drop_index(op.f('ix_chronicle_reviews_sys_update_datetime'), table_name='chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_reviews_sys_dept_id'), table_name='chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_reviews_sys_creator_id'), table_name='chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_reviews_sys_create_datetime'), table_name='chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_reviews_section_id'), table_name='chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_reviews_project_id'), table_name='chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_reviews_is_deleted'), table_name='chronicle_reviews')
    op.drop_table('chronicle_reviews')
    op.drop_index(op.f('ix_chronicle_references_sys_update_datetime'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_dept_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_creator_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_sys_create_datetime'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_section_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_project_id'), table_name='chronicle_references')
    op.drop_index(op.f('ix_chronicle_references_is_deleted'), table_name='chronicle_references')
    op.drop_table('chronicle_references')
    op.drop_index(op.f('ix_chronicle_projects_user_id'), table_name='chronicle_projects')
    op.drop_index(op.f('ix_chronicle_projects_sys_update_datetime'), table_name='chronicle_projects')
    op.drop_index(op.f('ix_chronicle_projects_sys_dept_id'), table_name='chronicle_projects')
    op.drop_index(op.f('ix_chronicle_projects_sys_creator_id'), table_name='chronicle_projects')
    op.drop_index(op.f('ix_chronicle_projects_sys_create_datetime'), table_name='chronicle_projects')
    op.drop_index(op.f('ix_chronicle_projects_status'), table_name='chronicle_projects')
    op.drop_index(op.f('ix_chronicle_projects_is_deleted'), table_name='chronicle_projects')
    op.drop_table('chronicle_projects')
    # ### end Alembic commands ###
