"""add rag table

Revision ID: db144068a72c
Revises: 4cfc2f527944
Create Date: 2026-06-01 15:32:32.358871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db144068a72c'
down_revision: Union[str, None] = '4cfc2f527944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chat_conversations',
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('user_id', sa.String(length=21), nullable=False, comment='用户ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='使用的大模型名称'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活（未关闭）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注/扩展信息'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chat_conversations_is_deleted'), 'rag_chat_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_chat_conversations_sys_create_datetime'), 'rag_chat_conversations', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_chat_conversations_sys_creator_id'), 'rag_chat_conversations', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_chat_conversations_sys_dept_id'), 'rag_chat_conversations', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_chat_conversations_sys_update_datetime'), 'rag_chat_conversations', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_rag_chat_conversations_user_id'), 'rag_chat_conversations', ['user_id'], unique=False)
    op.create_table('rag_chat_messages',
    sa.Column('conversation_id', sa.String(length=21), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='该条消息使用的模型'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='输入token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='输出token数'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='总token数'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chat_messages_conversation_id'), 'rag_chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_rag_chat_messages_is_deleted'), 'rag_chat_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_chat_messages_sys_create_datetime'), 'rag_chat_messages', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_chat_messages_sys_creator_id'), 'rag_chat_messages', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_chat_messages_sys_dept_id'), 'rag_chat_messages', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_chat_messages_sys_update_datetime'), 'rag_chat_messages', ['sys_update_datetime'], unique=False)
    op.create_table('rag_file_manager',
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件/文件夹名称'),
    sa.Column('file_type', sa.String(length=10), nullable=True, comment='类型: file/folder'),
    sa.Column('parent_id', sa.String(length=21), nullable=True, comment='父文件夹ID'),
    sa.Column('path', sa.Text(), nullable=False, comment='文件路径'),
    sa.Column('size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_ext', sa.String(length=50), nullable=True, comment='文件扩展名'),
    sa.Column('mime_type', sa.String(length=200), nullable=True, comment='MIME类型'),
    sa.Column('storage_path', sa.Text(), nullable=False, comment='存储路径'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='文件MD5'),
    sa.Column('scope', sa.String(length=20), nullable=True, comment='作用域: personal/shared'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='提取/OCR/编辑后的文本内容'),
    sa.Column('ocr_status', sa.String(length=20), nullable=True, comment='OCR状态: none/pending/completed/failed'),
    sa.Column('llm_status', sa.String(length=20), nullable=True, comment='多模态大模型识别状态: none/pending/completed/failed'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_file_manager_is_deleted'), 'rag_file_manager', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_file_manager_sys_create_datetime'), 'rag_file_manager', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_file_manager_sys_creator_id'), 'rag_file_manager', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_file_manager_sys_dept_id'), 'rag_file_manager', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_file_manager_sys_update_datetime'), 'rag_file_manager', ['sys_update_datetime'], unique=False)
    op.create_index('ix_rag_file_parent_type', 'rag_file_manager', ['parent_id', 'file_type'], unique=False)
    op.create_index('ix_rag_file_scope', 'rag_file_manager', ['scope'], unique=False)
    op.create_table('rag_knowledge_base',
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('kb_type', sa.String(length=20), nullable=True, comment='类型: user/demo'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rag_knowledge_base_is_deleted'), 'rag_knowledge_base', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_sys_create_datetime'), 'rag_knowledge_base', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_sys_creator_id'), 'rag_knowledge_base', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_sys_dept_id'), 'rag_knowledge_base', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_sys_update_datetime'), 'rag_knowledge_base', ['sys_update_datetime'], unique=False)
    op.create_table('rag_writer_conversations',
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('user_id', sa.String(length=21), nullable=False, comment='用户ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='使用的大模型名称'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_writer_conversations_is_deleted'), 'rag_writer_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_writer_conversations_sys_create_datetime'), 'rag_writer_conversations', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_writer_conversations_sys_creator_id'), 'rag_writer_conversations', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_conversations_sys_dept_id'), 'rag_writer_conversations', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_conversations_sys_update_datetime'), 'rag_writer_conversations', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_rag_writer_conversations_user_id'), 'rag_writer_conversations', ['user_id'], unique=False)
    op.create_table('rag_writer_documents',
    sa.Column('conversation_id', sa.String(length=21), nullable=False, comment='所属会话ID'),
    sa.Column('message_id', sa.String(length=21), nullable=False, comment='来源消息ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档内容（HTML格式）'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_writer_documents_conversation_id'), 'rag_writer_documents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_documents_is_deleted'), 'rag_writer_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_writer_documents_message_id'), 'rag_writer_documents', ['message_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_documents_sys_create_datetime'), 'rag_writer_documents', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_writer_documents_sys_creator_id'), 'rag_writer_documents', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_documents_sys_dept_id'), 'rag_writer_documents', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_documents_sys_update_datetime'), 'rag_writer_documents', ['sys_update_datetime'], unique=False)
    op.create_table('rag_writer_messages',
    sa.Column('conversation_id', sa.String(length=21), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='该条消息使用的模型'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_writer_messages_conversation_id'), 'rag_writer_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_messages_is_deleted'), 'rag_writer_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_writer_messages_sys_create_datetime'), 'rag_writer_messages', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_writer_messages_sys_creator_id'), 'rag_writer_messages', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_messages_sys_dept_id'), 'rag_writer_messages', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_writer_messages_sys_update_datetime'), 'rag_writer_messages', ['sys_update_datetime'], unique=False)
    op.create_table('rag_knowledge_base_file',
    sa.Column('kb_id', sa.String(length=21), nullable=False, comment='所属知识库'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('schema_json', sa.JSON(), nullable=True, comment='该文件的自定义Schema定义'),
    sa.Column('has_graph', sa.Boolean(), nullable=True, comment='是否已构建图谱'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['kb_id'], ['rag_knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_knowledge_base_file_is_deleted'), 'rag_knowledge_base_file', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_file_kb_id'), 'rag_knowledge_base_file', ['kb_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_file_sys_create_datetime'), 'rag_knowledge_base_file', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_file_sys_creator_id'), 'rag_knowledge_base_file', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_file_sys_dept_id'), 'rag_knowledge_base_file', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_file_sys_update_datetime'), 'rag_knowledge_base_file', ['sys_update_datetime'], unique=False)
    op.create_table('rag_knowledge_base_role',
    sa.Column('role_id', sa.String(length=21), nullable=False, comment='角色ID'),
    sa.Column('kb_id', sa.String(length=21), nullable=False, comment='知识库ID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['kb_id'], ['rag_knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'kb_id', name='uq_role_kb')
    )
    op.create_index(op.f('ix_rag_knowledge_base_role_is_deleted'), 'rag_knowledge_base_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_kb_id'), 'rag_knowledge_base_role', ['kb_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_role_id'), 'rag_knowledge_base_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_sys_create_datetime'), 'rag_knowledge_base_role', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_sys_creator_id'), 'rag_knowledge_base_role', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_sys_dept_id'), 'rag_knowledge_base_role', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_base_role_sys_update_datetime'), 'rag_knowledge_base_role', ['sys_update_datetime'], unique=False)
    op.create_table('rag_knowledge_graph',
    sa.Column('file_id', sa.String(length=21), nullable=False, comment='所属文件'),
    sa.Column('graph_data', sa.JSON(), nullable=True, comment='图谱结构数据(节点+边)'),
    sa.Column('chunks_data', sa.JSON(), nullable=True, comment='文本块数据 {chunk_id: text}'),
    sa.Column('built_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='构建时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.String(length=21), nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.ForeignKeyConstraint(['file_id'], ['rag_knowledge_base_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_rag_knowledge_graph_is_deleted'), 'rag_knowledge_graph', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_graph_sys_create_datetime'), 'rag_knowledge_graph', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_graph_sys_creator_id'), 'rag_knowledge_graph', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_graph_sys_dept_id'), 'rag_knowledge_graph', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_graph_sys_update_datetime'), 'rag_knowledge_graph', ['sys_update_datetime'], unique=False)
    op.drop_index(op.f('ix_demos_is_deleted'), table_name='demos')
    op.drop_index(op.f('ix_demos_sys_create_datetime'), table_name='demos')
    op.drop_index(op.f('ix_demos_sys_creator_id'), table_name='demos')
    op.drop_index(op.f('ix_demos_sys_dept_id'), table_name='demos')
    op.drop_index(op.f('ix_demos_sys_update_datetime'), table_name='demos')
    op.drop_table('demos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demos',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='内容'),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True, comment='状态：0=草稿，1=发布，2=归档'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True, comment='优先级：0=低，1=中，2=高'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.Column('sys_dept_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='部门ID（逻辑外键关联core_dept）'),
    sa.PrimaryKeyConstraint('id', name=op.f('demos_pkey'))
    )
    op.create_index(op.f('ix_demos_sys_update_datetime'), 'demos', ['sys_update_datetime'], unique=False)
    op.create_index(op.f('ix_demos_sys_dept_id'), 'demos', ['sys_dept_id'], unique=False)
    op.create_index(op.f('ix_demos_sys_creator_id'), 'demos', ['sys_creator_id'], unique=False)
    op.create_index(op.f('ix_demos_sys_create_datetime'), 'demos', ['sys_create_datetime'], unique=False)
    op.create_index(op.f('ix_demos_is_deleted'), 'demos', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_rag_knowledge_graph_sys_update_datetime'), table_name='rag_knowledge_graph')
    op.drop_index(op.f('ix_rag_knowledge_graph_sys_dept_id'), table_name='rag_knowledge_graph')
    op.drop_index(op.f('ix_rag_knowledge_graph_sys_creator_id'), table_name='rag_knowledge_graph')
    op.drop_index(op.f('ix_rag_knowledge_graph_sys_create_datetime'), table_name='rag_knowledge_graph')
    op.drop_index(op.f('ix_rag_knowledge_graph_is_deleted'), table_name='rag_knowledge_graph')
    op.drop_table('rag_knowledge_graph')
    op.drop_index(op.f('ix_rag_knowledge_base_role_sys_update_datetime'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_sys_dept_id'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_sys_creator_id'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_sys_create_datetime'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_role_id'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_kb_id'), table_name='rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_role_is_deleted'), table_name='rag_knowledge_base_role')
    op.drop_table('rag_knowledge_base_role')
    op.drop_index(op.f('ix_rag_knowledge_base_file_sys_update_datetime'), table_name='rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_file_sys_dept_id'), table_name='rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_file_sys_creator_id'), table_name='rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_file_sys_create_datetime'), table_name='rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_file_kb_id'), table_name='rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_knowledge_base_file_is_deleted'), table_name='rag_knowledge_base_file')
    op.drop_table('rag_knowledge_base_file')
    op.drop_index(op.f('ix_rag_writer_messages_sys_update_datetime'), table_name='rag_writer_messages')
    op.drop_index(op.f('ix_rag_writer_messages_sys_dept_id'), table_name='rag_writer_messages')
    op.drop_index(op.f('ix_rag_writer_messages_sys_creator_id'), table_name='rag_writer_messages')
    op.drop_index(op.f('ix_rag_writer_messages_sys_create_datetime'), table_name='rag_writer_messages')
    op.drop_index(op.f('ix_rag_writer_messages_is_deleted'), table_name='rag_writer_messages')
    op.drop_index(op.f('ix_rag_writer_messages_conversation_id'), table_name='rag_writer_messages')
    op.drop_table('rag_writer_messages')
    op.drop_index(op.f('ix_rag_writer_documents_sys_update_datetime'), table_name='rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_documents_sys_dept_id'), table_name='rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_documents_sys_creator_id'), table_name='rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_documents_sys_create_datetime'), table_name='rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_documents_message_id'), table_name='rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_documents_is_deleted'), table_name='rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_documents_conversation_id'), table_name='rag_writer_documents')
    op.drop_table('rag_writer_documents')
    op.drop_index(op.f('ix_rag_writer_conversations_user_id'), table_name='rag_writer_conversations')
    op.drop_index(op.f('ix_rag_writer_conversations_sys_update_datetime'), table_name='rag_writer_conversations')
    op.drop_index(op.f('ix_rag_writer_conversations_sys_dept_id'), table_name='rag_writer_conversations')
    op.drop_index(op.f('ix_rag_writer_conversations_sys_creator_id'), table_name='rag_writer_conversations')
    op.drop_index(op.f('ix_rag_writer_conversations_sys_create_datetime'), table_name='rag_writer_conversations')
    op.drop_index(op.f('ix_rag_writer_conversations_is_deleted'), table_name='rag_writer_conversations')
    op.drop_table('rag_writer_conversations')
    op.drop_index(op.f('ix_rag_knowledge_base_sys_update_datetime'), table_name='rag_knowledge_base')
    op.drop_index(op.f('ix_rag_knowledge_base_sys_dept_id'), table_name='rag_knowledge_base')
    op.drop_index(op.f('ix_rag_knowledge_base_sys_creator_id'), table_name='rag_knowledge_base')
    op.drop_index(op.f('ix_rag_knowledge_base_sys_create_datetime'), table_name='rag_knowledge_base')
    op.drop_index(op.f('ix_rag_knowledge_base_is_deleted'), table_name='rag_knowledge_base')
    op.drop_table('rag_knowledge_base')
    op.drop_index('ix_rag_file_scope', table_name='rag_file_manager')
    op.drop_index('ix_rag_file_parent_type', table_name='rag_file_manager')
    op.drop_index(op.f('ix_rag_file_manager_sys_update_datetime'), table_name='rag_file_manager')
    op.drop_index(op.f('ix_rag_file_manager_sys_dept_id'), table_name='rag_file_manager')
    op.drop_index(op.f('ix_rag_file_manager_sys_creator_id'), table_name='rag_file_manager')
    op.drop_index(op.f('ix_rag_file_manager_sys_create_datetime'), table_name='rag_file_manager')
    op.drop_index(op.f('ix_rag_file_manager_is_deleted'), table_name='rag_file_manager')
    op.drop_table('rag_file_manager')
    op.drop_index(op.f('ix_rag_chat_messages_sys_update_datetime'), table_name='rag_chat_messages')
    op.drop_index(op.f('ix_rag_chat_messages_sys_dept_id'), table_name='rag_chat_messages')
    op.drop_index(op.f('ix_rag_chat_messages_sys_creator_id'), table_name='rag_chat_messages')
    op.drop_index(op.f('ix_rag_chat_messages_sys_create_datetime'), table_name='rag_chat_messages')
    op.drop_index(op.f('ix_rag_chat_messages_is_deleted'), table_name='rag_chat_messages')
    op.drop_index(op.f('ix_rag_chat_messages_conversation_id'), table_name='rag_chat_messages')
    op.drop_table('rag_chat_messages')
    op.drop_index(op.f('ix_rag_chat_conversations_user_id'), table_name='rag_chat_conversations')
    op.drop_index(op.f('ix_rag_chat_conversations_sys_update_datetime'), table_name='rag_chat_conversations')
    op.drop_index(op.f('ix_rag_chat_conversations_sys_dept_id'), table_name='rag_chat_conversations')
    op.drop_index(op.f('ix_rag_chat_conversations_sys_creator_id'), table_name='rag_chat_conversations')
    op.drop_index(op.f('ix_rag_chat_conversations_sys_create_datetime'), table_name='rag_chat_conversations')
    op.drop_index(op.f('ix_rag_chat_conversations_is_deleted'), table_name='rag_chat_conversations')
    op.drop_table('rag_chat_conversations')
    # ### end Alembic commands ###
